version: "3.8"
name: my_app

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db 
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: testdb
      MYSQL_PORT: 3306
      FLASK_APP: main.py
      FLASK_ENV: development
    networks:
      - app_network

networks:
  app_network:
    external: true
