version: "3.8"
name: my_app

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nana1123!
      MYSQL_DATABASE: testdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

networks:
  app_network:
    external: true
volumes:
  mysql_data:
