"""empty message

Revision ID: 974f149531b1
Revises: 
Create Date: 2024-11-25 22:47:52.922267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974f149531b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=True),
    sa.Column('written_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_addr', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ip_addr')

    op.drop_table('board')
    # ### end Alembic commands ###
